2023-10-02 19:40:19 - INFO - [base_logger.py : initialize_logger - 75] :: Initialized logger for the service [usermanagement] :: [SUCCESS]
2023-10-02 19:40:19 - INFO - [app_manager.py : __init__ - 16] :: Initialized cmn_logger with value: <Logger usermanagement (DEBUG)>
2023-10-02 19:40:19 - INFO - [app_manager.py : create_app_instance - 20] :: Received Service [usermanagement]
2023-10-02 19:40:19 - INFO - [app_manager.py : create_app_instance - 22] :: Created of Flask Application Instance for service [usermanagement]
2023-10-02 19:40:19 - INFO - [app_manager.py : read_json_schema - 70] :: Received Schema File Path : /Users/kamalsaidevarapalli/Desktop/Workshop/PyPortalAdminstration/src/usermanagement_service/schemas/headers/reg_headers_schema.json
2023-10-02 19:40:19 - INFO - [app_manager.py : read_json_schema - 83] :: Schema Validation True
2023-10-02 19:40:19 - INFO - [app_manager.py : read_json_schema - 70] :: Received Schema File Path : /Users/kamalsaidevarapalli/Desktop/Workshop/PyPortalAdminstration/src/usermanagement_service/schemas/headers/getuser_headers_schema.json
2023-10-02 19:40:19 - INFO - [app_manager.py : read_json_schema - 83] :: Schema Validation True
2023-10-02 19:40:19 - INFO - [app_manager.py : read_json_schema - 70] :: Received Schema File Path : /Users/kamalsaidevarapalli/Desktop/Workshop/PyPortalAdminstration/src/usermanagement_service/schemas/headers/del_user_headers_schema.json
2023-10-02 19:40:19 - INFO - [app_manager.py : read_json_schema - 83] :: Schema Validation True
2023-10-02 19:40:19 - INFO - [app_manager.py : read_json_schema - 70] :: Received Schema File Path : /Users/kamalsaidevarapalli/Desktop/Workshop/PyPortalAdminstration/src/usermanagement_service/schemas/requests/register_user/req_schema.json
2023-10-02 19:40:19 - INFO - [app_manager.py : read_json_schema - 83] :: Schema Validation True
2023-10-02 19:40:19 - INFO - [app_manager.py : create_blueprint_instance - 46] :: Created Blueprint :: <Blueprint 'usermanagement_bp'> for the Application service ::usermanagement
2023-10-02 19:40:19 - INFO - [db_manager.py : __init__ - 56] :: Initialized cmn_logger with value: <Logger usermanagement (DEBUG)>
2023-10-02 19:40:19 - INFO - [db_manager.py : __init__ - 56] :: Initialized db_driver with value: postgresql
2023-10-02 19:40:19 - INFO - [db_manager.py : __init__ - 56] :: Initialized db_user with value: usermanageradmin
2023-10-02 19:40:19 - INFO - [db_manager.py : __init__ - 56] :: Initialized db_password with value: Ishi#06041995
2023-10-02 19:40:19 - INFO - [db_manager.py : __init__ - 56] :: Initialized db_ip_address with value: 127.0.0.1
2023-10-02 19:40:19 - INFO - [db_manager.py : __init__ - 56] :: Initialized db_port with value: 3304
2023-10-02 19:40:19 - INFO - [db_manager.py : __init__ - 56] :: Initialized db_name with value: USERS
2023-10-02 19:40:19 - INFO - [db_manager.py : __init__ - 56] :: Initialized db_pool_size with value: 30
2023-10-02 19:40:19 - INFO - [db_manager.py : __init__ - 56] :: Initialized db_pool_recycle with value: 60
2023-10-02 19:40:19 - INFO - [db_manager.py : __init__ - 56] :: Initialized db_pool_timeout with value: 10
2023-10-02 19:40:19 - INFO - [db_manager.py : __init__ - 56] :: Initialized db_pool_max_overflow with value: 20
2023-10-02 19:40:19 - INFO - [db_manager.py : __init__ - 56] :: Initialized base with value: <class 'sqlalchemy.orm.decl_api.Base'>
2023-10-02 19:40:19 - INFO - [db_manager.py : __init__ - 56] :: Initialized retry_interval with value: 5
2023-10-02 19:40:19 - INFO - [db_manager.py : __init__ - 56] :: Initialized max_retries with value: 3
2023-10-02 19:40:19 - INFO - [db_manager.py : create_db_engine_for_service - 73] :: Creating DB-Engine using DatabaseURI for Service :: [usermanagement]
2023-10-02 19:40:19 - INFO - [db_manager.py : get_database_uri - 60] :: Preparing DatabaseURI for Service :: [usermanagement]  ::
2023-10-02 19:40:19 - INFO - [db_manager.py : get_database_uri - 62] :: Prepared DatabaseURI for Service :: [usermanagement] - postgresql://usermanageradmin:Ishi%2306041995@127.0.0.1:3304/USERS ::
2023-10-02 19:40:19 - INFO - [db_manager.py : create_db_engine_for_service - 76] :: Created DB-Engine using DatabaseURI for Service :: [Engine(postgresql://usermanageradmin:***@127.0.0.1:3304/USERS)]
2023-10-02 19:40:19 - INFO - [db_manager.py : check_database_connectivity - 218] :: Current Connection status set to :: False for the service :: usermanagement
2023-10-02 19:40:19 - INFO - [db_manager.py : check_database_connectivity - 221] :: Trying to establish the connection to the database :: [IN-PROGRESS]
2023-10-02 19:40:19 - INFO - [db_manager.py : check_database_connectivity - 223] :: Established the connection to the database :: [SUCCESS]
2023-10-02 19:40:19 - INFO - [db_manager.py : check_database_connectivity - 225] :: Current Connection status set to :: True for the service :: usermanagement
2023-10-02 19:40:19 - INFO - [db_manager.py : check_database_connectivity - 228] :: Closing the Current Connection as the connection was established for the service :: usermanagement
2023-10-02 19:40:19 - INFO - [db_manager.py : get_database_uri - 60] :: Preparing DatabaseURI for Service :: [usermanagement]  ::
2023-10-02 19:40:19 - INFO - [db_manager.py : get_database_uri - 62] :: Prepared DatabaseURI for Service :: [usermanagement] - postgresql://usermanageradmin:Ishi%2306041995@127.0.0.1:3304/USERS ::
2023-10-02 19:40:19 - INFO - [db_manager.py : get_database_uri - 60] :: Preparing DatabaseURI for Service :: [usermanagement]  ::
2023-10-02 19:40:19 - INFO - [db_manager.py : get_database_uri - 62] :: Prepared DatabaseURI for Service :: [usermanagement] - postgresql://usermanageradmin:Ishi%2306041995@127.0.0.1:3304/USERS ::
2023-10-02 19:40:19 - INFO - [db_manager.py : create_database_for_service - 100] :: Database already exists :: USERS
2023-10-02 19:40:19 - INFO - [db_manager.py : create_tables_associated_to_db_model - 238] :: Trying to create the tables if not present in the database...
2023-10-02 19:40:19 - INFO - [db_manager.py : create_tables_associated_to_db_model - 240] :: Going to create the tables ...
2023-10-02 19:40:19 - INFO - [db_manager.py : create_tables_associated_to_db_model - 243] :: Created the tables ...
2023-10-02 19:40:19 - INFO - [db_manager.py : bind_db_app - 108] :: Binding SQLALCHEMY  to Application Instance for Service :: [usermanagement]
2023-10-02 19:40:19 - INFO - [db_manager.py : bind_db_app - 110] :: Bound SQLALCHEMY :: [<SQLAlchemy>] to Application Instance for Service :: [usermanagement]
2023-10-02 19:40:19 - INFO - [db_manager.py : migrate_db_bind_app - 118] :: Binding the db :: [<SQLAlchemy>] to app instance :: [<Flask 'usermanagement'>] for migrations
2023-10-02 19:40:19 - INFO - [db_manager.py : migrate_db_bind_app - 120] :: Bound the db :: [<SQLAlchemy>] to app instance :: [<Flask 'usermanagement'>] for migrations
2023-10-02 19:40:19 - INFO - [db_manager.py : create_pool_of_connections - 128] :: Creating Pool of connections for Service ==>[usermanagement] :: [STARTED]
2023-10-02 19:40:19 - INFO - [db_manager.py : create_pool_of_connections - 131] :: Created Pool of connections for Service ==>[usermanagement] :: [SUCCESS]
2023-10-02 19:40:19 - INFO - [db_manager.py : create_session_maker_to_connectio_pool - 139] :: Creating session using pool of connections  :: [STARTED]
2023-10-02 19:40:19 - INFO - [db_manager.py : create_session_maker_to_connectio_pool - 140] :: Creating  a session maker for database interactions
2023-10-02 19:40:19 - INFO - [db_manager.py : create_session_maker_to_connectio_pool - 142] :: Created session using Pool_info :: <sqlalchemy.pool.impl.QueuePool object at 0x1051daf70>
2023-10-02 19:40:19 - INFO - [db_manager.py : create_session_maker_to_connectio_pool - 143] :: Initialised a session maker for database interactions sessionmaker(class_='Session', bind=Engine(postgresql://usermanageradmin:***@127.0.0.1:3304/USERS), autoflush=True, expire_on_commit=True)
2023-10-02 19:40:19 - INFO - [db_manager.py : display_pool_info - 189] :: #---------------------------------[ POOL INFO ]----------------------------------------#
2023-10-02 19:40:19 - INFO - [db_manager.py : display_pool_info - 190] :: Displaying Pool Info for Service ==>[usermanagement]
2023-10-02 19:40:19 - INFO - [db_manager.py : display_pool_info - 191] :: Current Pool Info :: <sqlalchemy.pool.impl.QueuePool object at 0x1051daf70> - ID: 4380798832
2023-10-02 19:40:19 - INFO - [db_manager.py : display_pool_info - 192] :: Current Pool Size :: 30
2023-10-02 19:40:19 - INFO - [db_manager.py : display_pool_info - 193] :: Checked Out Connections from Pool: 0
2023-10-02 19:40:19 - INFO - [db_manager.py : display_pool_info - 194] :: Checked in Connections available in Pool: 0
2023-10-02 19:40:19 - INFO - [db_manager.py : display_pool_info - 195] :: Current Pool Overflow Info: -30
2023-10-02 19:40:19 - INFO - [db_manager.py : display_pool_info - 196] :: #---------------------------------[ POOL INFO ]----------------------------------------#
2023-10-02 19:40:19 - INFO - [app_manager.py : register_blueprint_for_service - 55] :: Registering blueprints to the service :: <Flask 'usermanagement'>
2023-10-02 19:40:19 - INFO - [app_manager.py : display_registered_blueprints_for_service - 63] :: Added Blueprints :: /static/<path:filename>
2023-10-02 19:40:19 - INFO - [app_manager.py : display_registered_blueprints_for_service - 63] :: Added Blueprints :: /api/v1/airliner/registerUser
2023-10-02 19:40:19 - INFO - [grpc_base_server.py : __init__ - 14] :: Initialized cmn_logger with value: <Logger usermanagement (DEBUG)>
2023-10-02 19:40:19 - INFO - [grpc_base_server.py : __init__ - 14] :: Initialized grpc_server_ip with value: 127.0.0.1
2023-10-02 19:40:19 - INFO - [grpc_base_server.py : __init__ - 14] :: Initialized grpc_server_port with value: 50051
2023-10-02 19:40:19 - INFO - [grpc_base_server.py : __init__ - 14] :: Initialized max_workers_for_service with value: 4
2023-10-02 19:40:19 - INFO - [grpc_base_server.py : __init__ - 14] :: Initialized base_grpc_server with value: <grpc._server._Server object at 0x10553b670>
2023-10-02 19:40:19 - INFO - [grpc_base_server.py : bind_ip_port_server - 20] :: Registered GRPC server :: 127.0.0.1:50051
2023-10-02 19:40:19 - INFO - [grpc_base_server.py : bind_rpc_method_server - 28] :: Registered RPC call to the server of :: <grpc._server._Server object at 0x10553b670> :: <class 'src.usermanagement_service.user_management_grpc.user_grpc_server.UserValidationForTokenGenerationService'>
2023-10-02 19:40:19 - INFO - [grpc_base_server.py : start_base_server - 31] :: Started GRPC Server
2023-10-02 19:40:19 - INFO - [usermanagement.py : <module> - 7] :: Bound USER-MANAGEMENT-SERVICE at IP-ADDRESS:PORT :: 0.0.0.0:9091
2023-10-02 19:40:19 - INFO - [usermanagement.py : <module> - 8] :: Started the USER-MANAGEMENT server ...
2023-10-02 19:40:19 - INFO - [usermanagement.py : <module> - 9] :: Application is ready to server traffic.
